version: '3.8'
services:
  postgres:
    container_name: "social_service_db"
    image: 'postgres:latest'
    restart: always
    user: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=social_service
    ports:
      - '3500:5432'
  redis:
    image: 'redis:latest'
    restart: always
    user: redis
    ports:
      - '6379:6379'
volumes:
  postgres_volume:
