//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "friendship_history_events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::friendship_history::Entity")]
    FriendshipHistory,
}

impl Related<super::friendship_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FriendshipHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
