//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "friendship_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub friendship_id: i32,
    pub event: String,
    pub acting_user: String,
    pub timestamp: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::friendships::Entity",
        from = "Column::FriendshipId",
        to = "super::friendships::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Friendships,
}

impl Related<super::friendships::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Friendships.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
