//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

pub use super::friendship_history::Entity as FriendshipHistory;
pub use super::friendship_history_events::Entity as FriendshipHistoryEvents;
pub use super::friendships::Entity as Friendships;
