#!/bin/bash

# Run `cargo fmt` on all modified Rust source files.
for file in $(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(rs)$')
do
  if [[ -f $file ]]; then
    cargo fmt --manifest-path=$PWD/Cargo.toml -- $file
    git add $file
  fi
done
