name: Validations

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start DB
        run: |
          docker-compose up -d
          docker exec social-service_postgres_1 bash -c "until pg_isready; do sleep 1; done"
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: RUST_LOG=debug cargo test --verbose
      - name: Stop containers
        if: always()
        run: docker-compose down
